import { Activity, Play, Plus, RefreshCw, Waypoints } from 'lucide-react'
import { useState } from 'react'
import type { CommandResult, KeyDetails } from '../types/api'
import { ResponseRenderer } from '../components/ResponseRenderer'

export function StreamsPage({ execute, inspect }: { execute: (command: string) => Promise<CommandResult>; inspect: (key: string) => Promise<KeyDetails> }) {
  const [key, setKey] = useState('events'); const [fields, setFields] = useState('user alice action login'); const [entries, setEntries] = useState<KeyDetails>(); const [last, setLast] = useState<CommandResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>()
  const add = async () => { setBusy(true); setError(undefined); try { const command = `XADD ${key.trim()} * ${fields.trim()}`; setLast(await execute(command)); setEntries(await inspect(key.trim())) } catch (e) { setError(e instanceof Error ? e.message : 'Stream request failed') } finally { setBusy(false) } }
  const refresh = async () => { if (!key.trim()) return; setBusy(true); try { setEntries(await inspect(key.trim())) } catch (e) { setError(e instanceof Error ? e.message : 'Inspection failed') } finally { setBusy(false) } }
  return <section className="page-stack"><div className="page-heading"><div><div className="eyebrow">ORDERED EVENT LOG</div><h1>Streams</h1><p>Create and inspect stream entries through XADD and XRANGE.</p></div><div className="page-icon"><Waypoints size={20} /></div></div><div className="stream-controls"><div className="field-group"><label>STREAM KEY</label><input value={key} onChange={e => setKey(e.target.value)} /></div><div className="field-group grow"><label>FIELDS <span>space-separated key value pairs</span></label><input value={fields} onChange={e => setFields(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void add() }} /></div><button className="button primary" onClick={() => void add()} disabled={busy || !key.trim() || !fields.trim()}>{busy ? <span className="spinner" /> : <Plus size={15} />} XADD</button></div><div className="stream-toolbar"><div><span className="live-label"><span className="pulse-dot" /> HTTP + RESP</span><span className="muted">Live WebSocket streaming is planned separately.</span></div><button className="button subtle" onClick={() => void refresh()} disabled={busy}><RefreshCw size={14} /> Refresh XRANGE</button></div>{error && <div className="inline-error static">{error}</div>}{last && <div className="last-command"><span className="eyebrow">LAST COMMAND</span><code>XADD {key} * {fields}</code><ResponseRenderer response={last.response} error={last.error} /></div>}<div className="stream-result"><div className="stream-result-head"><div><span className="eyebrow">XRANGE {key} - +</span><h2>Stream entries</h2></div><Activity size={17} className="muted" /></div>{entries?.response ? <StreamTable response={entries.response} /> : <div className="empty-state compact"><Waypoints size={22} /><strong>No entries loaded</strong><span>Publish an entry or refresh a known stream.</span></div>}</div></section>
}

function StreamTable({ response }: { response: KeyDetails['response'] }) { const values = response?.type === 'array' ? response.value as NonNullable<KeyDetails['response']>[] : []; return <div className="stream-table">{values.map((entry, i) => { const parts = entry.type === 'array' ? entry.value as NonNullable<KeyDetails['response']>[] : []; const fields = parts[1]?.type === 'array' ? parts[1].value as NonNullable<KeyDetails['response']>[] : []; return <div className="stream-entry" key={i}><code className="stream-id">{String(parts[0]?.value)}</code><div className="stream-fields">{Array.from({ length: Math.ceil(fields.length / 2) }, (_, j) => <span key={j}><b>{String(fields[j * 2]?.value)}</b>{String(fields[j * 2 + 1]?.value)}</span>)}</div></div> })}</div> }
