import { AlertTriangle, GitBranch, Play, RotateCcw, ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import type { CommandResult } from '../types/api'
import { ResponseRenderer } from '../components/ResponseRenderer'

export function TransactionsPage({ execute, session, setSession }: { execute: (command: string, session?: string) => Promise<CommandResult>; session?: string; setSession: (session?: string) => void }) {
  const [state, setState] = useState<'IDLE' | 'ACTIVE' | 'EXECUTED'>('IDLE')
  const [queued, setQueued] = useState<string[]>([]); const [results, setResults] = useState<CommandResult>(); const [input, setInput] = useState('SET counter 20'); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>()
  const run = async (command: string, explicitSession?: string) => { const verb = command.trim().split(/\s+/, 1)[0]?.toUpperCase(); setBusy(true); setError(undefined); try { const result = await execute(command, explicitSession ?? session); if (verb === 'MULTI' && result.ok) { setState('ACTIVE') } else if (verb === 'EXEC') { setResults(result); setState('EXECUTED'); setQueued([]); setSession(undefined) } else if (verb === 'DISCARD') { setState('IDLE'); setQueued([]); setSession(undefined) } else if (state === 'ACTIVE' && result.ok) setQueued([...queued, command]) } catch (e) { setError(e instanceof Error ? e.message : 'Transaction request failed') } finally { setBusy(false) } }
  const begin = () => { const id = session || crypto.randomUUID(); setSession(id); void run('MULTI', id) }
  return <section className="page-stack"><div className="page-heading"><div><div className="eyebrow">CONNECTION STATE</div><h1>Transactions</h1><p>Demonstrate connection-scoped MULTI / EXEC behavior through a stable Redis session.</p></div><div className="page-icon"><GitBranch size={20} /></div></div><div className="transaction-banner"><div className={`transaction-state ${state.toLowerCase()}`}><span className="state-dot" /><span>Transaction state</span><strong>{state}</strong></div><div className="transaction-session"><span className="eyebrow">REDIS SESSION</span><code>{session || 'not started'}</code></div></div><div className="transaction-grid"><div className="transaction-workbench"><div className="card-heading"><div><span className="eyebrow">COMMAND QUEUE</span><h2>Interactive transaction</h2></div>{state === 'IDLE' ? <button className="button primary" onClick={begin} disabled={busy}><Play size={14} /> Start MULTI</button> : <div className="transaction-actions"><button className="button ghost" onClick={() => void run('DISCARD')} disabled={busy}><RotateCcw size={14} /> Discard</button><button className="button primary" onClick={() => void run('EXEC')} disabled={busy}><Play size={14} /> Execute</button></div>}</div><div className="queue-list">{queued.length === 0 ? <div className="queue-empty"><span>1</span><p>{state === 'IDLE' ? 'Start MULTI to begin queueing commands.' : 'Commands sent while ACTIVE appear here.'}</p></div> : queued.map((command, i) => <div className="queue-item" key={`${command}-${i}`}><span>{String(i + 1).padStart(2, '0')}</span><code>{command}</code><b>QUEUED</b></div>)}</div>{state === 'ACTIVE' && <div className="queue-input"><span>›</span><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && input.trim()) void run(input.trim()) }} /><button className="button subtle" onClick={() => { if (input.trim()) void run(input.trim()) }}>Queue</button></div>}{error && <div className="inline-error static">{error}</div>}{results && <div className="execution-results"><span className="eyebrow">EXECUTION RESULTS</span><ResponseRenderer response={results.response} error={results.error} /></div>}</div><aside className="transaction-notes"><div className="note-icon"><ShieldAlert size={18} /></div><h3>Connection-scoped</h3><p>Redis transactions only work when MULTI, queued commands, and EXEC share one TCP connection.</p><div className="note-divider" /><div className="note-icon warning"><AlertTriangle size={18} /></div><h3>No rollback</h3><p>Runtime errors are returned per command. Later commands still execute; MyRedis does not provide rollback.</p><button className="try-example" onClick={() => { setInput('INCR foo'); if (state === 'IDLE') begin() }}>Try runtime-error example <Play size={13} /></button></aside></div></section>
}
